### ISSUE TITLE
Issue when changing default crate names

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [SimonFlash/TeslaCrate#12]
[21:24:57] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: teslacrate/INFO: Loading config...
[21:24:57] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: teslacrate/ERROR: An unexpected error occurred initializing rewards.conf: configurate.typesafe.config.ConfigException$Parse: Reader: 14: Expecting close brace } or a comma, got '=' (if you intended '=' to be part of a key or string value, try enclosing the key or value in double quotes)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: java.io.IOException: configurate.typesafe.config.ConfigException$Parse: Reader: 14: Expecting close brace } or a comma, got '=' (if you intended '=' to be part of a key or string value, try enclosing the key or value in double quotes)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:145)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at ninja.leaping.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:58)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.mcsimonflash.sponge.teslalibs.configuration.ConfigHolder.<init>(ConfigHolder.java:21)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.mcsimonflash.sponge.teslalibs.configuration.ConfigHolder.of(ConfigHolder.java:32)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.mcsimonflash.sponge.teslacrate.internal.Config.loadConfig(Config.java:103)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.mcsimonflash.sponge.teslacrate.internal.Config.load(Config.java:51)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.mcsimonflash.sponge.teslacrate.TeslaCrate.onStarting(TeslaCrate.java:67)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at org.spongepowered.common.event.listener.GameStartingServerEventListener_TeslaCrate_onStarting134.handle(Unknown Source)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:248)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:272)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:24:57] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:24:58] [Netty Server IO #2/INFO] [FML]: Disconnecting Player: Server is still starting! Please wait before reconnecting.
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:794)
[21:24:58] [Netty Server IO #4/INFO] [FML]: Disconnecting Player: Server is still starting! Please wait before reconnecting.
[21:24:58] [Netty Server IO #3/INFO] [FML]: Disconnecting Player: Server is still starting! Please wait before reconnecting.
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[21:24:58] [Server thread/INFO] [STDERR]: [com.mcsimonflash.sponge.teslacrate.internal.Config:loadConfig:106]: 	at java.lang.Thread.run(Unknown Source)
[21:24:58] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: configurate.typesafe.config.ConfigException$Parse: Reader: 14: Expecting close brace } or a comma, got '=' (if you intended '=' to be part of a key or string value, try enclosing the key or value in double quotes)
[21:24:58] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
[21:24:58] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
[21:24:58] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:526)
[21:24:58] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247)
[21:24:58] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:456)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:456)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.impl.Parseable.parse(Parseable.java:299)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at configurate.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:622)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:174)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:55)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:136)
[21:24:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 44 more
[21:24:59] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: teslacrate/ERROR: Configuration loading has halted.

**Comment by SimonFlash** [comment]
You config isn't formatted properly. Please do not use GitHub for support, if you need assistance you should join the [support discord](https://discord.gg/4wayq37).
